services:
  - type: web
    name: backend
    env: docker
    plan: free
    dockerfilePath: ./backend/Dockerfile
    envVars:
      - key: DATABASE_URL
        sync: false
    healthCheckPath: /
    autoDeploy: true
    buildCommand: docker build -t backend ./backend
    startCommand: uvicorn main:app --host 0.0.0.0 --port 8000

  - type: web
    name: frontend
    env: docker
    plan: free
    dockerfilePath: ./frontend/Dockerfile
    envVars:
      - key: BACKEND_URL
        sync: false
    healthCheckPath: /
    autoDeploy: true
    buildCommand: docker build -t frontend ./frontend
    startCommand: streamlit run app.py --server.port 8501 --server.address 0.0.0.0

  - type: database
    name: db
    plan: free
    databaseType: postgres
    version: 17
    region: oregon
    envVars:
      - key: POSTGRES_USER
        value: adam
      - key: POSTGRES_PASSWORD
        value: adam1234
      - key: POSTGRES_DB
        value: Repertoire
